<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-RFDNNRIC" failures="1" tests="10" name="testNG Learning" time="0.307" errors="0" timestamp="2021-12-18T17:45:43 IST">
  <testcase classname="test.firstTest" name="test1" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.firstTest.test1(firstTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="test.firstTest" name="test18" time="0.006"/>
  <testcase classname="test.firstTest" name="test18" time="0.002"/>
  <testcase classname="test.firstTest" name="test18" time="0.004"/>
  <testcase classname="test.firstTest" name="test2" time="0.01"/>
  <testcase classname="test.secondTest" name="test4" time="0.002"/>
  <testcase classname="test.secondTest" name="test5" time="0.007"/>
  <testcase classname="test.thirdTest" name="test6" time="0.005"/>
  <testcase classname="test.thirdTest" name="test7" time="0.002"/>
  <testcase classname="test.thirdTest" name="test8" time="0.003"/>
  <testcase classname="test.secondTest" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- testNG Learning -->
